# Generated by Django 4.2.7 on 2023-11-20 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Costumer',
                'verbose_name_plural': 'Costumers',
            },
        ),
        migrations.CreateModel(
            name='HearthProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('degree', models.IntegerField(choices=[(1, 'Low'), (2, 'High')])),
                ('code_costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olisaude.costumer')),
            ],
            options={
                'verbose_name': 'Hearth Problem',
                'verbose_name_plural': 'Hearth Problems',
            },
        ),
    ]
