# Generated by Django 4.2.7 on 2023-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olisaude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
