# Generated by Django 4.2.7 on 2023-11-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olisaude', '0002_alter_costumer_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
